name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-api, upload-api, recommend-api, scrap-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  

    - name: Build and Push Docker image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}/${{ matrix.service }}
        docker build -t $IMAGE_NAME:latest ./${{ matrix.service }}
        docker push $IMAGE_NAME:latest

    - name: Update ECS service
      if: ${{ matrix.service != 'scrap-service' }}  # scrap-service is not exposed
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ matrix.service }} \
          --force-new-deployment \
          --region us-east-1